### ISSUE TITLE
Python 3 version gives a Socket Error, then imaplib2 crashes

### ISSUE THREAD

**Issue by ghost** [jazzband/imaplib2#2]
Tested on various flavours of Ubuntu with python 3.6, 3.5 and 3.4 using the latest (3.05) version, using several IMAP mail providers.

**Here is a small test and the result:**

```
import imaplib2

oImap = imaplib2.IMAP4_SSL('imap.gmail.com', 993, debug=4)
```

```
  35:34.18 MainThread imaplib2 version 3.05
  35:34.18 MainThread imaplib2 debug level 4, buffer level 3
  35:34.34 MainThread connected to imap.gmail.com on port 993
  35:34.34 imap.gmail.com writer starting
  35:34.35 imap.gmail.com reader starting using poll
  35:34.35 MainThread _request_push(continuation, welcome, {}) = b'CPNE0'
  35:34.35 imap.gmail.com reader poll => [(13, 1)]
  35:34.35 MainThread welcome:b'CPNE0'.ready.wait
  35:34.35 imap.gmail.com reader rcvd 69
  35:34.35 MainThread _close_threads
  35:34.35 imap.gmail.com reader < b'* OK Gimap ready for requests from xxx\r\n'
  35:34.35 imap.gmail.com writer finished
  35:34.35 MainThread call shutdown
  35:34.35 imap.gmail.com reader poll => [(13, 17)]
  35:34.35 imap.gmail.com reader last 20 log messages:
  35:34.34 imap.gmail.com writer starting
  35:34.35 imap.gmail.com reader starting using poll
  35:34.35 MainThread _close_threads
  35:34.35 imap.gmail.com writer finished
  35:34.35 MainThread call shutdown
  35:34.35 imap.gmail.com reader socket error: <class 'ValueError'> - Read on closed or unwrapped SSL socket.
  35:34.35 imap.gmail.com reader finished
  35:34.45 imap.gmail.com handler starting
  35:34.45 imap.gmail.com handler terminating: 'Terminated'
  35:34.45 imap.gmail.com handler welcome:b'CPNE0'.ready.set
  35:34.45 imap.gmail.com handler state_change_free.set
  35:34.45 imap.gmail.com handler finished

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/imaplib2.py", line 2093, in __init__
    IMAP4.__init__(self, host, port, debug, debug_file, identifier, timeout, debug_buf_lvl)
  File "/usr/lib/python3/dist-packages/imaplib2.py", line 375, in __init__
    self.welcome = self._request_push(name='welcome', tag='continuation').get_response('IMAP4 protocol error: %s')[1]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ghost** [comment]
I have done some further testing on multiple computers with various systems, and it appears the bug affects 32-bit installations only.

**Comment by ghost** [comment]
Just tested on Ubuntu 18.04 - the python 3 version still crashes on a 32-bit system, while it works on a 64-bit install.

**Comment by chris001** [comment]
* Interesting, which 32 bit OS you try and it failed on, ubuntu 18.04 and 16.04 for intel i386 or i586 kernel?
* Could you share output result of running same code on 64-bit cleanly without that traceback.

**Comment by ghost** [comment]
@chris001 

I have tried it on i386 versions of 17.04, 17.10 and 18.04.

Here it is on 18.04 amd64, works just fine, no crash:

```
  27:28.89 MainThread imaplib2 version 3.05
  27:28.91 MainThread imaplib2 debug level 4, buffer level 3
  27:29.04 MainThread connected to imap.gmail.com on port 993
  27:29.05 imap.gmail.com writer starting
  27:29.05 imap.gmail.com reader starting using poll
  27:29.05 MainThread _request_push(continuation, welcome, {}) = b'HKOI0'
  27:29.05 imap.gmail.com reader < b'* OK Gimap ready for requests from x.x.x.x p10mb307524837wrj\r\n'
  27:29.05 MainThread welcome:b'HKOI0'.ready.wait
  27:29.15 imap.gmail.com handler starting
  27:29.15 imap.gmail.com handler _request_pop(continuation, (False, b'* OK Gimap ready for requests from x.x.x.x p10mb307524837wrj')) [0] = b'HKOI0'
  27:29.15 imap.gmail.com handler welcome:b'HKOI0'.ready.set
  27:29.15 imap.gmail.com handler state_change_free.set
  27:29.15 MainThread state => NONAUTH
  27:29.15 MainThread [async] CAPABILITY ()
  27:29.15 MainThread state_change_pending.acquire
  27:29.15 MainThread state_change_pending.release
  27:29.16 MainThread _request_push(b'HKOI1', CAPABILITY, {}) = b'HKOI1'
  27:29.16 MainThread data=b'HKOI1 CAPABILITY'
  27:29.16 MainThread CAPABILITY:b'HKOI1'.ready.wait
  27:29.16 imap.gmail.com writer > b'HKOI1 CAPABILITY\r\n'
  27:29.20 imap.gmail.com reader < b'* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH\r\n'
  27:29.20 imap.gmail.com reader < b'HKOI1 OK Thats all she wrote! p10mb307524837wrj\r\n'
  27:29.20 imap.gmail.com handler _request_pop(b'HKOI1', ('OK', [b'Thats all she wrote! p10mb307524837wrj'])) [0] = b'HKOI1'
  27:29.20 imap.gmail.com handler CAPABILITY:b'HKOI1'.ready.set
  27:29.20 MainThread _untagged_response(OK, ?, CAPABILITY) => [b'IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SA
  27:29.20 imap.gmail.com handler state_change_free.set
  27:29.20 MainThread CAPABILITY: ('IMAP4REV1', 'UNSELECT', 'IDLE', 'NAMESPACE', 'QUOTA', 'ID', 'XLIST', 'CHILDREN', 'X-GM-EXT-1', 'XYZZY', 'SASL-IR', 'AUTH=XOAUTH2', 'AUTH=PLAIN', 'AUTH=PLAIN-CLIENTTOKEN', 'AUTH=OAUTHBEARER', 'AUTH=XOAUTH')
```

**Comment by chris001** [comment]
@bcoe 
Have you ever tried code similar to the above on i386?  Does it also crash for you? Any suggestion?
